FoodSalesWEB/FoodSalesWEB/Controllers/FoodController.cs
using FoodSalesWEB.Helpers;
using FoodSalesWEB.Models;
using FoodSalesWEB.Models.API;
using FoodSalesWEB.Models.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodSalesWEB.Controllers
{
    public class FoodController : Controller
    {
        public ActionResult Edit(int foodID)
        {
            FoodInfoModels foodInfoModels = new FoodInfoModels();
            try
            {
                iHttpClient iHttpClient = new iHttpClient();

                #region Get Category
                var resultCategory = iHttpClient.GetAsync(UrlHelpers.categoryList);
                if (resultCategory.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<List<z_category>>>(resultCategory.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        return View(foodInfoModels);
                    }
                    else
                    {
                        List<SelectListItem> li = new List<SelectListItem>();
                        foreach (var e in resultModel.data)
                        {
                            li.Add(new SelectListItem { Text = e.Category.ToString(), Value = e.Category.ToString() });
                        }
                        var emptip = new SelectListItem()
                        {
                            Value = "",
                            Text = "[กรุณาเลือก]"
                        };
                        li.Insert(0, emptip);
                        foodInfoModels.SelectCategoryList = li;
                    }
                }
                else
                {
                    ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    ViewBag.MsgError = resultCategory.Message;
                    return View(foodInfoModels);
                }
                #endregion

                #region Get City
                var resultCity = iHttpClient.GetAsync(UrlHelpers.cityList);
                if (resultCity.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<List<z_city>>>(resultCity.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        return View(foodInfoModels);
                    }
                    else
                    {
                        List<SelectListItem> li = new List<SelectListItem>();
                        foreach (var e in resultModel.data)
                        {
                            li.Add(new SelectListItem { Text = e.City.ToString(), Value = e.City.ToString() });
                        }
                        var emptip = new SelectListItem()
                        {
                            Value = "",
                            Text = "[กรุณาเลือก]"
                        };
                        li.Insert(0, emptip);
                        foodInfoModels.SelectCityList = li;
                    }
                }
                else
                {
                    ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    ViewBag.MsgError = resultCity.Message;
                    return View(foodInfoModels);
                }
                #endregion

                #region Get region
                var resultRegion = iHttpClient.GetAsync(UrlHelpers.regionList);
                if (resultRegion.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<List<z_region>>>(resultRegion.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        return View(foodInfoModels);
                    }
                    else
                    {
                        List<SelectListItem> li = new List<SelectListItem>();
                        foreach (var e in resultModel.data)
                        {
                            li.Add(new SelectListItem { Text = e.Region.ToString(), Value = e.Region.ToString() });
                        }
                        var emptip = new SelectListItem()
                        {
                            Value = "",
                            Text = "[กรุณาเลือก]"
                        };
                        li.Insert(0, emptip);
                        foodInfoModels.SelectRegionList = li;
                    }
                }
                else
                {
                    ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    ViewBag.MsgError = resultRegion.Message;
                    return View(foodInfoModels);
                }
                #endregion

                #region Get Data Info
                var resultData = iHttpClient.GetAsync(UrlHelpers.foodByID + foodID);
                if (resultData.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<m_food>>(resultData.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    }
                    else
                    {
                        foodInfoModels.m_Food = new mFood()
                        {
                            Quantity = resultModel.data.Quantity,
                            Category = resultModel.data.Category,
                            City = resultModel.data.City,
                            foodID = resultModel.data.foodID,
                            OrderDate = resultModel.data.OrderDate,
                            Product = resultModel.data.Product,
                            Region = resultModel.data.Region,
                            TotalPrice = resultModel.data.TotalPrice,
                            UnitPrice = resultModel.data.UnitPrice
                        };
                    }
                    return View(foodInfoModels);
                }
                else
                {
                    ViewBag.MsgError = resultData.Message;
                    ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    return View(foodInfoModels);
                }
                #endregion
            }
            catch (Exception ex)
            {
                ViewBag.UrlGoTo = Url.Action("Index", "Home");
                ViewBag.MsgError = ex.Message.Replace("\r\n", "");
                return View(foodInfoModels);
            }

        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "Edit")]
        public ActionResult Edit(FoodInfoModels foodInfoModels)
        {
            try
            {
                iHttpClient iHttpClient = new iHttpClient();

                #region Get Category
                var resultCategory = iHttpClient.GetAsync(UrlHelpers.categoryList);
                if (resultCategory.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<List<z_category>>>(resultCategory.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        return View(foodInfoModels);
                    }
                    else
                    {
                        List<SelectListItem> li = new List<SelectListItem>();
                        foreach (var e in resultModel.data)
                        {
                            li.Add(new SelectListItem { Text = e.Category.ToString(), Value = e.Category.ToString() });
                        }
                        var emptip = new SelectListItem()
                        {
                            Value = "",
                            Text = "[กรุณาเลือก]"
                        };
                        li.Insert(0, emptip);
                        foodInfoModels.SelectCategoryList = li;
                    }
                }
                else
                {
                    ViewBag.UrlGoTo = Url.Action("Index", "Home");
                    ViewBag.MsgError = resultCategory.Message;
                    return View(foodInfoModels);
                }
                #endregion

                #region Get City
                var resultCity = iHttpClient.GetAsync(UrlHelpers.cityList);
                if (resultCity.StatusCode == 200)
                {
                    var resultModel = JsonConvert.DeserializeObject<OutputModels<List<z_city>>>(resultCity.Message);
                    if (resultModel.error_code != 1 || resultModel.sub_code != 1)
                    {
                        ViewBag.MsgError = string.Format("{0} {1} {2}", resultModel.error_code, resultModel.sub_code, resultModel.message);
                        return View(foodInfoModels);
                    }
                    else
                    {
                        List<SelectListItem> li = new List<SelectListItem>();
                        foreach (var e in resultModel.data)
                        {

FoodSalesWEB/FoodSalesWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>@ViewBag.Title</title>

    <script src="~/Scripts/jquery-3.6.0.min.js"></script>

    <!-- CSS files -->
    <link href="~/Content/css/tabler.min.css" rel="stylesheet" />
    <link href="~/Content/css/tabler-flags.min.css" rel="stylesheet" />
    <link href="~/Content/css/tabler-payments.min.css" rel="stylesheet" />
    <link href="~/Content/css/tabler-vendors.min.css" rel="stylesheet" />
    <link href="~/Content/css/demo.min.css" rel="stylesheet" />
    <link href="~/Scripts/libs/datatables/datatables.min.css" rel="stylesheet" />
    <link href="~/Scripts/select/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/css/demo.css" rel="stylesheet" />
    <!-- Online -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" />

    

    <style type="text/css">
        * {
            font-family: 'Varela Round', sans-serif;
        }

        .field-validation-valid {
            display: none;
        }

        .img-logo {
            display: block;
            margin-left: auto;
            width: 80%;
        }

        .text-logo-color {
            color: #D73A31;
        }

        .icon-top-line {
            width: 1.75rem;
            height: 1.75rem;
            font-size: 1.25rem;
            vertical-align: bottom;
            /*stroke-width: 1.5;*/
        }

        #table-scroll {
            height: auto;
            overflow: auto;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Food Sales Web", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add", "Add", "Food", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    <!-- Scripts JS -->
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.blockUI.js"></script>
    <script src="~/Scripts/libs/datatables/datatables.min.js"></script>
    <script src="~/Scripts/select/select2/js/select2.full.min.js"></script>
    <script src="~/Scripts/libs/litepicker/dist/litepicker.js" defer></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Scripts Libs JS -->
    <script src="~/Scripts/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/Scripts/libs/jsvectormap/dist/js/jsvectormap.min.js"></script>
    <script src="~/Scripts/libs/jsvectormap/dist/maps/world.js"></script>

    <!-- Scripts Tabler Core -->
    <script src="~/Scripts/js/tabler.min.js"></script>
    <script src="~/Scripts/js/demo.min.js"></script>

    <!-- Scripts Online -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

<script type="text/javascript">

    $(document).ready(function () {

        $.unblockUI();
        console.log("unblockUI");
    });

    // ## blockUI ##
    //Center the element
    $.fn.center = function () {
        this.css("position", "absolute");
        this.css("top", ($(window).height() - this.height()) / 2 + $(window).scrollTop() + "px");
        this.css("left", ($(window).width() - this.width()) / 2 + $(window).scrollLeft() + "px");
        return this;
    }

    function blockUI() {
        $.blockUI({
            css: {
                backgroundColor: 'transparent',
                border: 'none'
            },
            message: '<div class="spinner-grow text-primary" role="status" style="width:50px;height:50px"> </div>',
            baseZ: 1500,
            overlayCSS: {
                backgroundColor: '#FFFFFF',
                opacity: 0.7,
                cursor: 'wait'
            }
        });
        $('.blockUI.blockMsg').center();
    }
    //End blockUI

    // ## sweetalert2 ##

    // *Success type
    function onOkSuccess(msg,url)
    {
        swal({
            title: "รายงานผล",
            text: msg,
            type: "success"
        }, function () {
            if (url != null && url != "") {
                location.replace(url);
            }
        });
    }

    @if (!string.IsNullOrWhiteSpace(ViewBag.MsgSuccess))
    {
        @:onOkSuccess("@(ViewBag.MsgSuccess)","@Html.Raw(ViewBag.UrlGoTo)");
    }

    // *Error type
    function onOkError(msg, url) {
        swal({
            title: "เกิดข้อผิดพลาด",
            text: msg,
            type: "error"
        }, function () {
            if (url != null && url != "") {
                window.location = url;
            }
        });
    }

    @if (!string.IsNullOrWhiteSpace(ViewBag.MsgError))
    {
        @:onOkError("@(ViewBag.MsgError)","@Html.Raw(ViewBag.UrlGoTo)");
    }

    // *Warning type
    function onOkWarning(msg, url) {
        swal({
            title: "แจ้งเตือน",
            text: msg,
            type: "warning"
        }, function () {
            if (url != null && url != "") {
                location.replace(url);
            }
        });
    }

    @if (!string.IsNullOrWhiteSpace(ViewBag.MsgWarning))
    {
        @:onOkWarning("@(ViewBag.MsgWarning)", "@Html.Raw(ViewBag.UrlGoTo)");
    }

    // ## End sweetalert2 ##


    //Select2
    $(function () {
        //Initialize Select2 Elements
        $('.select2').select2()

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })

        $("input[data-bootstrap-switch]").each(function () {
            $(this).bootstrapSwitch('state', $(this).prop('checked'));
        })
    })
    //End Select2

</script>